apiVersion: v1
kind: Service
metadata:
  name: api-mock
  namespace: default
  labels:
    app.kubernetes.io/name: api-mock
    app.kubernetes.io/instance: api-mock
    app.kubernetes.io/version: 0.0.1
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: argo-cd
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: api-mock
    app.kubernetes.io/instance: api-mock
    app.kubernetes.io/component: api
