apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argo-cd
spec:
  project: cd
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: sealed-secrets
      targetRevision: 1.5.3
      helm:
        valueFiles:
          - $values/infrastructure/charts-values/production/kube-system/sealed-secrets.yaml
    - repoURL: https://github.com/juan131/k8s-gitops-template.git
      targetRevision: production
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      # Delete resources when Argo CD detects the resource is no longer defined in Git
      prune: true
    syncOptions:
      # Ensures that namespace specified as the application destination exists in the destination cluster
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
